name: Continuous Integration Tester

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tarobot-builder
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
        python -m coverage erase
    - name: Test the code with unittest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m coverage run --branch -a -m unittest discover tarobot/tests --verbose
    - name: Code coverage report
      run: |
        python -m coverage report --omit="tarobot/tests/**" --fail-under=85
    - name: Run a smoke test with the latest code
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -m tarobot --show-prompt card-list --teller "Dr Seuss"
